### ISSUE TITLE
脚本运行报错，大佬可以看看吗

### ISSUE THREAD

**Issue by NiceSeason** [ForeverFancy/PKU-ncov-AutoReport#1]
不太懂python，大佬可以看看是哪里错了吗，控制台如下：
login...
begin report...
Traceback (most recent call last):
  File "Autoreport.py", line 133, in <module>
    autorepoter.main_loop()
  File "Autoreport.py", line 23, in main_loop
    self.report()
  File "Autoreport.py", line 40, in report
    data = json.loads(data)
  File "C:\Users\cumtmhs\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\cumtmhs\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\cumtmhs\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 2 (char 23)

data.json如下：
{
	"now_address": "1"
	"gps_now_address": 
	"now_province": "340000"
	"gps_province": 
	"now_city": "340100"
	"gps_city": 
	"now_detail": 
	"is_inschool": "2"
	"body_condition": "1"
	"body_condition_detail": 
	"now_status": "1"
	"now_status_detail": 
	"has_fever": "0"
	"last_touch_sars": "0"
	"last_touch_sars_date": 
	"last_touch_sars_detail": 
	"other_detail": 
}

**Comment by ForeverFancy** [comment]
请检查一下你的 json 文件，看上去格式不对。value 为空的地方要用 `""`。
